spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/foodiebuddy}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
resilience4j.circuitbreaker.instances.orderServiceCB.register-health-indicator=true
resilience4j.circuitbreaker.instances.orderServiceCB.sliding-window-size=10
resilience4j.circuitbreaker.instances.orderServiceCB.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.orderServiceCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.orderServiceCB.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.orderServiceCB.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.orderServiceCB.automatic-transition-from-open-to-half-open-enabled=true
